### ISSUE TITLE
Does not display as expected

### ISSUE THREAD

**Issue by elokanugrah** [nickyrabit/CarRentalAppConceptIUIMotionLayout#2]
Hi, I found this incredible example of motionlayout implementation, but after I tried it didn't look as expected. The app is only displays hello world textview.

So, where is the motionlayout?

**Comment by nickyrabit** [comment]
Hello,  please check again I have forgotten to upload all branches in this repo. 
You can now find the code in the master branch as well as cLayout branch
Thank you so much for your interest.
Also please don't update the libraries yet the code might break I'm not sure though
